import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Masthead from "../components/masthead";
import AboutUs from "../components/aboutus";
import Skills from "../components/skills";
import Navbar from "../components/navbar";
import TrustetBy from "../components/trustedby";
import ContactUs from "../components/contactus";
import Footer from "../components/footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Agon Ademaj - Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/favicon.png' />
      </Head>
      <Navbar />
      <Masthead />
      <AboutUs />
      <Skills />
      <TrustetBy />
      <ContactUs />
      <Footer />
    </div>
  );
};

export default Home;
