import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import Project from "../components/project";
import ProjectHead from "../components/projecthead";

const Projects: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Agon Ademaj - Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/favicon.png' />
      </Head>

      <Navbar />
      <ProjectHead />
      <Project />
      <Footer />
    </div>
  );
};

export default Projects;
